"""New tebles

Revision ID: 077cedc0eba7
Revises: 679cd576ecff
Create Date: 2025-06-13 10:43:01.437695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077cedc0eba7'
down_revision: Union[str, None] = '679cd576ecff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distancia', sa.String(length=20), nullable=True),
    sa.Column('ciudad', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciudad', sa.VARCHAR(length=20), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=30), nullable=True),
    sa.Column('longitud', sa.VARCHAR(length=15), nullable=True),
    sa.Column('latitud', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hotel', sa.Column('id_ubicacion', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hotel', 'ubicacion', ['id_ubicacion'], ['id'])
    op.add_column('plan', sa.Column('id_ubicacion', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plan', 'ubicacion', ['id_ubicacion'], ['id'])
    op.add_column('reserva', sa.Column('id_ruta', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reserva', 'ruta', ['id_ruta'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserva', type_='foreignkey')
    op.drop_column('reserva', 'id_ruta')
    op.drop_constraint(None, 'plan', type_='foreignkey')
    op.drop_column('plan', 'id_ubicacion')
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.drop_column('hotel', 'id_ubicacion')
    op.drop_table('ubicacion')
    op.drop_table('ruta')
    # ### end Alembic commands ###
