"""add tursta table

Revision ID: 23afeb00f45b
Revises: 
Create Date: 2025-06-09 10:24:47.958596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23afeb00f45b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('ciudad_residencia', sa.VARCHAR(length=20), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('identificacion', sa.Integer(), nullable=True),
    sa.Column('contraseña', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turista')
    # ### end Alembic commands ###
