"""add administrador, favorito, chat, informe, notificacion table

Revision ID: 664d9924c61f
Revises: bdf5f4bb1c3d
Create Date: 2025-06-09 20:13:02.660673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664d9924c61f'
down_revision: Union[str, None] = 'bdf5f4bb1c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('identificacion', sa.Integer(), nullable=True),
    sa.Column('contraseña', sa.VARCHAR(length=10), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_turista', sa.Integer(), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('mensaje', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('id_turista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('id_chat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacion')
    op.drop_table('informe')
    op.drop_table('chat')
    op.drop_table('favorito')
    op.drop_table('administrador')
    # ### end Alembic commands ###
