"""add reserva table

Revision ID: 6fce11bbbe0e
Revises: 23afeb00f45b
Create Date: 2025-06-09 11:09:52.641997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fce11bbbe0e'
down_revision: Union[str, None] = '23afeb00f45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('id_turista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    # ### end Alembic commands ###
