"""cambios hotel

Revision ID: 9cfe696d8fdf
Revises: 077cedc0eba7
Create Date: 2025-06-13 10:50:46.874367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9cfe696d8fdf'
down_revision: Union[str, None] = '077cedc0eba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hotel_ibfk_1', 'hotel', type_='foreignkey')
    op.drop_column('hotel', 'id_ubicacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('id_ubicacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('hotel_ibfk_1', 'hotel', 'ubicacion', ['id_ubicacion'], ['id'])
    # ### end Alembic commands ###
