"""add rol, plan  tables

Revision ID: bdf5f4bb1c3d
Revises: 6c7a1b5eb9fe
Create Date: 2025-06-09 20:05:51.043493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf5f4bb1c3d'
down_revision: Union[str, None] = '6c7a1b5eb9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('ubicacion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('numero_dias', sa.Integer(), nullable=True),
    sa.Column('numero_noches', sa.Integer(), nullable=True),
    sa.Column('horario', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol')
    op.drop_table('plan')
    # ### end Alembic commands ###
