"""'BaseDatos'

Revision ID: 3795dbbf59c1
Revises: 
Create Date: 2025-05-22 19:58:37.953555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3795dbbf59c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('ubicacion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=100), nullable=True),
    sa.Column('numero_dias', sa.Integer(), nullable=True),
    sa.Column('numero_noches', sa.Integer(), nullable=True),
    sa.Column('horario', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('identificacion', sa.Integer(), nullable=True),
    sa.Column('contraseña', sa.VARCHAR(length=10), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('celular', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('ciudad_residencia', sa.VARCHAR(length=20), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('identificacion', sa.Integer(), nullable=True),
    sa.Column('contraseña', sa.VARCHAR(length=10), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('mensaje', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('id_turista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_turista', sa.Integer(), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('id_turista', sa.Integer(), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('id_chat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('reserva')
    op.drop_table('informes')
    op.drop_table('favoritos')
    op.drop_table('chat')
    op.drop_table('turista')
    op.drop_table('administrador')
    op.drop_table('rol')
    op.drop_table('plan')
    # ### end Alembic commands ###
