from .turista import Turista
from .reserva import Reserva
from .plan import Plan
from .administrador import Administrador
from .favorito import Favorito
from .chat import Chat
from .informe import Informe
from .notificacion import Notificacion
from .instancia import Instancia
from .hotel import Hotel 
from .rol import Rol
from .ubicacion import Ubicacion
from .ruta import Ruta